// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKl_YIV2egsZsyJH3AJ64Yq5nsrckJV-Q',
    appId: '1:2529627840:android:c947ae3ce6cdfd37c12725',
    messagingSenderId: '2529627840',
    projectId: 'chat-app-62c1b',
    storageBucket: 'chat-app-62c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaTeuIu__shVVgOL8D2Lko3dPvzGDbSSo',
    appId: '1:2529627840:ios:2acb05dee805093ec12725',
    messagingSenderId: '2529627840',
    projectId: 'chat-app-62c1b',
    storageBucket: 'chat-app-62c1b.appspot.com',
    androidClientId: '2529627840-iii8b6l0as5a3ohc7qdls56qpp9rhn8m.apps.googleusercontent.com',
    iosClientId: '2529627840-vmbge3nh9lclaluhu881he5qgedjd4kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
